name: e621
description: A wrapper for the e621 api, complete with models that handle JSON responses and built-in rate-limiting.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  j_util:
    path: ../j_util/
