import 'dart:ui';

// import 'package:flutter/material.dart';
// import 'package:fuzzy/util/html_colors.dart' as css;

const colorMap = {
      "--color-background": Color(0xff020f23),
      "--color-foreground": Color(0xff152f56),
      "--color-section": Color(0xff1f3c67),
      "--color-section-lighten-5": Color(0xff25477b),
      "--color-section-lighten-10": Color(0xff2b538e),
      "--color-section-darken-5": Color(0xff193153),
      "--color-table-border": Color(0xff2b538e),
      "--color-section-pending": Color(0xff1f3c67),
      "--color-section-pending-border": Color(0xff020f23),
      "--color-text": Color(0xffffffff),
      "--color-text-muted": Color(0xff999999),
      "--color-text-white": Color(0xffffffff),
      "--color-text-table-header": Color(0xffe6e6e6),
      "--color-link": Color(0xffb4c7d9),
      "--color-link-hover": Color(0xffe9f2fa),
      "--color-link-active": Color(0xffe8c446),
      "--color-button-active": Color(0xffe8c446),
      "--color-link-last-page": Color(0xff666666),
      "--color-success": Color(0xff006400),
      "--color-success-darken-5": Color(0xff004b00),
      "--color-danger": Color(0xFF800000), //css.maroon,
      "--color-danger-darken-5": Color(0xff670000),
      "--color-danger-darken-10": Color(0xff4d0000),
      "--color-warning": Color(0xFFA0522D), //css.sienna,
      "--color-warning-darken-5": Color(0xff8c4827),
      "--color-rating-explicit": Color(0xffe45f5f),
      "--color-rating-questionable": Color(0xffffe666),
      "--color-rating-safe": Color(0xff3e9e49),
      "--color-score-positive": Color(0xff3e9e49),
      "--color-score-negative": Color(0xffe45f5f),
      "--color-active-tag": Color(0xff006ffa),
      "--color-dtext-quote": Color(0xffb4c7d9),
      "--color-dtext-code": Color(0xffffe380),
      "--color-dtext-section": Color(0xff17a2b8),
      "--color-user-member": Color(0xffb4c7d9),
      "--color-user-member-alt": Color(0xff2e76b4),
      "--color-user-privileged": Color(0xffb4c7d9),
      "--color-user-privileged-alt": Color(0xff2e76b4),
      "--color-user-blocked": Color(0xffb4c7d9),
      "--color-user-blocked-alt": Color(0xff2e76b4),
      "--color-user-former-staff": Color(0xff78dca5),
      "--color-user-former-staff-alt": Color(0xff4da073),
      "--color-user-janitor": Color(0xffd82828),
      "--color-user-janitor-alt": Color(0xffcc5151),
      "--color-user-moderator": Color(0xffd82828),
      "--color-user-moderator-alt": Color(0xffcc5151),
      "--color-user-admin": Color(0xffe69500),
      "--color-user-admin-alt": Color(0xff9d6703),
      "--color-tag-general": Color(0xffb4c7d9),
      "--color-tag-general-alt": Color(0xff2e76b4),
      "--color-tag-artist": Color(0xfff2ac08),
      "--color-tag-artist-alt": Color(0xfffbd67f),
      "--color-tag-copyright": Color(0xffdd00dd),
      "--color-tag-copyright-alt": Color(0xffff5eff),
      "--color-tag-character": Color(0xff00aa00),
      "--color-tag-character-alt": Color(0xff2bff2b),
      "--color-tag-species": Color(0xffed5d1f),
      "--color-tag-species-alt": Color(0xfff6b295),
      "--color-tag-invalid": Color(0xffff3d3d),
      "--color-tag-invalid-alt": Color(0xffffbdbd),
      "--color-tag-meta": Color(0xffffffff),
      "--color-tag-meta-alt": Color(0xff666666),
      "--color-tag-lore": Color(0xff228822),
      "--color-tag-lore-alt": Color(0xff5fdb5f),
      "--color-tag-pool": Color(0xFFF5DEB3), //css.wheat,
      "--color-tag-pool-alt": Color(0xffd0b27a),
      "--color-spoiler-link": Color(0xffb4c7d9),
      "--color-spoiler-link-hover": Color(0xffe9f2fa),
    },
    background = Color(0xff020f23),
    foreground = Color(0xff152f56),
    section = Color(0xff1f3c67),
    sectionLighten5 = Color(0xff25477b),
    sectionLighten10 = Color(0xff2b538e),
    sectionDarken5 = Color(0xff193153),
    tableBorder = Color(0xff2b538e),
    sectionPending = Color(0xff1f3c67),
    sectionPendingBorder = Color(0xff020f23),
    text = Color(0xffffffff),
    textMuted = Color(0xff999999),
    textWhite = Color(0xffffffff),
    textTableHeader = Color(0xffe6e6e6),
    link = Color(0xffb4c7d9),
    linkHover = Color(0xffe9f2fa),
    linkActive = Color(0xffe8c446),
    buttonActive = Color(0xffe8c446),
    linkLastPage = Color(0xff666666),
    success = Color(0xff006400),
    successDarken5 = Color(0xff004b00),
    danger = Color(0xFF800000), //css.maroon,
    dangerDarken5 = Color(0xff670000),
    dangerDarken10 = Color(0xff4d0000),
    warning = Color(0xFFA0522D), //css.sienna,
    warningDarken5 = Color(0xff8c4827),
    ratingExplicit = Color(0xffe45f5f),
    ratingQuestionable = Color(0xffffe666),
    ratingSafe = Color(0xff3e9e49),
    scorePositive = Color(0xff3e9e49),
    scoreNegative = Color(0xffe45f5f),
    activeTag = Color(0xff006ffa),
    dtextQuote = Color(0xffb4c7d9),
    dtextCode = Color(0xffffe380),
    dtextSection = Color(0xff17a2b8),
    userMember = Color(0xffb4c7d9),
    userMemberAlt = Color(0xff2e76b4),
    userPrivileged = Color(0xffb4c7d9),
    userPrivilegedAlt = Color(0xff2e76b4),
    userBlocked = Color(0xffb4c7d9),
    userBlockedAlt = Color(0xff2e76b4),
    userFormerStaff = Color(0xff78dca5),
    userFormerStaffAlt = Color(0xff4da073),
    userJanitor = Color(0xffd82828),
    userJanitorAlt = Color(0xffcc5151),
    userModerator = Color(0xffd82828),
    userModeratorAlt = Color(0xffcc5151),
    userAdmin = Color(0xffe69500),
    userAdminAlt = Color(0xff9d6703),
    tagGeneral = Color(0xffb4c7d9),
    tagGeneralAlt = Color(0xff2e76b4),
    tagArtist = Color(0xfff2ac08),
    tagArtistAlt = Color(0xfffbd67f),
    tagCopyright = Color(0xffdd00dd),
    tagCopyrightAlt = Color(0xffff5eff),
    tagCharacter = Color(0xff00aa00),
    tagCharacterAlt = Color(0xff2bff2b),
    tagSpecies = Color(0xffed5d1f),
    tagSpeciesAlt = Color(0xfff6b295),
    tagInvalid = Color(0xffff3d3d),
    tagInvalidAlt = Color(0xffffbdbd),
    tagMeta = Color(0xffffffff),
    tagMetaAlt = Color(0xff666666),
    tagLore = Color(0xff228822),
    tagLoreAlt = Color(0xff5fdb5f),
    tagPool = Color(0xFFF5DEB3), //css.wheat,
    tagPoolAlt = Color(0xffd0b27a),
    spoilerLink = Color(0xffb4c7d9),
    spoilerLinkHover = Color(0xffe9f2fa);
// const e6Theme = ThemeData.raw(
//   colorScheme: ColorScheme(
//     brightness: Brightness.dark,
//     primary: section,
//     onPrimary: text,
//     secondary: sectionLighten10,
//     onSecondary: text,
//     error: danger,
//     onError: text,
//     surface: foreground,
//     onSurface: text,
//   ),

// );
